# https://railsguides.jp/configuring.html#%E3%82%AB%E3%82%B9%E3%82%BF%E3%83%A0%E8%A8%AD%E5%AE%9A
# i18n で変更になる値は locales 以下に。
shared:
  domain: kanken-j1.fkoba.com
  host: kanken-j1.fkoba.com  # 正確には FQDN (https://www.cman.jp/network/term/domain/)
  blog_url: https://blog.kanken-j1.fkoba.com

development:
  host: <%= ENV["DEVELOPMENT_HOST"] %>
  port: 3000
  # url: "http://#{config.host}:#{config.port}"
  # こういうことやりたければ YAML はやめておいた方がいい
  url: "http://<%= ENV["DEVELOPMENT_HOST"] %>:3000"

production:
  url: https://kanken-j1.fkoba.com
